### ISSUE TITLE
playlists 

### ISSUE THREAD

**Issue by Dotdk** [DennisvHest/MapMaven#161]
im still pretty new but the playlists not show up in my quest 2 vr set. tryed to find the map its say and its suggest i play a expert map when i only have done easy so far. 
does u know why i cant find the listes in beatsaber in my headset?

**Comment by DennisvHest** [comment]
Hey @Dotdk, thanks for trying out Map Maven.

Do you have the [PlaylistManager](https://github.com/rithik-b/PlaylistManager) mod installed for Beat Saber? This is required to see custom playlists in Beat Saber.

Also, I assume you have the quest 2 headset plugged into your PC and you are playing Beat Saber from your PC. Map Maven does not work for Beat Saber directly running on the quest headset.

**Comment by Dotdk** [comment]
Yes il found out looking great with the mod u have maked like it alot
my beginner/noob nes find out what where wrong il use BSManeger and have putted wrong placement for install in to the software u maked so now they show up then i just need to find out why it suggest me expert maps when i have maps with easy deficulties in there

**Comment by DennisvHest** [comment]
Okay, good to hear.

I think because you haven't played many ranked maps, it is having some trouble finding recommended maps to play for you. I suggest changing the 'Min predicted accuracy' filter on the improve page to around 65. I think it will then find maps that are good for you to play.

**Comment by Dotdk** [comment]
Allright i try that is it not possible to make a filter under the dymamic part to set it to 65 or only under the other section?
Sorry il try to understand how it works its amasing job u have maked with it

**Comment by DennisvHest** [comment]
Yeah, you can make a dynamic playlist. The 'Improvement maps' preset will contain the same maps as on the improvement page. If you click on the preset, you can set the 'estimated accuracy' to >=65.

![image](https://github.com/DennisvHest/MapMaven/assets/18610083/ce3cf59a-c707-40f9-b0ce-d9232636a6c6)

**Comment by Dotdk** [comment]
Oh dident know it would give the same outcome played some erlier and will take a round later Agian liked the list it maked for me Think i shuld play a bit around with the playlist maker
