### ISSUE TITLE
Suggestion: Show which maps are in which playlist in the general maps overview vial small logos

### ISSUE THREAD

**Issue by TheSangral** [DennisvHest/MapMaven#210]
An issue I find myself having with the program and what I don't like is that I can't see which of my maps are already in a playlist. 
Like, I wanted to use this tool for sorting stuff into playlist, but my problem is, when I download a bunch of playlist and I want to combine them into one, lets say I have a hundred of Disney songs I want to put into 1 playlist but the are split up between 2 already and some aren't even in any playlist, nothing in this tool currently can show me which are in which playlist, or not even which of my maps are in a playlist at all. Like a little logo on each map would help out a lot here. Or at least when I click on map details it should me which playlist it's in.

Visual Suggestion:

![Screenshot 2024-08-17 142023](https://github.com/user-attachments/assets/80fcbb34-8e36-4721-aaba-4ce3a8c8be8d)

**Comment by DennisvHest** [comment]
Good suggestion! Will look into it. Thanks!

**Comment by DennisvHest** [comment]
This is coming in the next release.

**Comment by DennisvHest** [comment]
This feature has been released in version 1.6.2
